spring:
  application:
    name: user-service
  output:
    ansi:
      enabled: always
server:
  port: 8081
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka